version: '3'

services:

  frontend-base:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    image: frontend-base/gitflashcard:0.1
    container_name: frontend-base-gitflashcard

  frontend-dev:
    image: frontend-base/gitflashcard:0.1
    container_name: frontend-dev-gitflashcard
    volumes:
      - .:/frontend
    working_dir: /frontend
    ports:
      - "80:3000"
    command: /bin/sh -c "npm run start:local"
    depends_on:
      - frontend-base

networks:
  backend:
    driver: "bridge"
