version: '3'

services:

  web-base:
    build:
      context: .
      dockerfile: Dockerfile_web_base
    image: web-base/gitflashcard:0.1
    container_name: web-base-gitflashcard

  web-dev:
    image: web-base/gitflashcard:0.1
    container_name: web-dev-gitflashcard
    volumes:
      - .:/website
    working_dir: /website
    tty: true
    ports:
      - "3000:3000"
    command: /bin/sh -c "npm run start"
    depends_on:
      - web-base

  web-build:
    image: web-base/gitflashcard:0.1
    container_name: web-build-gitflashcard
    volumes:
      - .:/website
    working_dir: /website
    tty: true
    command: /bin/sh -c "npm install && npm run build"
    depends_on:
      - web-base
